// Code generated by generate_randomized_freepool.py. DO NOT EDIT.

// Dummy file to force the go compiler to honor go:linkname directives. See
//
// https://github.com/golang/go/issues/15006
// http://www.alangpierce.com/blog/2016/03/17/adventures-in-go-accessing-unexported-functions/
